version: "3.0"
services:
  elasticsearch:
          container_name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
          environment:
              - discovery.type=single-node
              - xpack.security.enabled=$ELASTIC_SECURITY
              - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
          ulimits:
              memlock:
                  soft: -1
                  hard: -1
          volumes:
              - elastic-data:/usr/share/elasticsearch/data
          restart: unless-stopped
          ports:
              - "9200:9200"
              - "9300:9300"
          healthcheck:
              test:
                  [
                  "CMD-SHELL",
                  "curl --fail http://localhost:9200 || exit 1",
                  ]
              interval: 10s
              timeout: 10s
              retries: 120
volumes:
  elastic-data: