version: "1.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    volumes:
      - elast_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type: single-node"
      - "xpack.security.enabled: true"
    ports:
      - 9200:9200
volumes:
  elast_data: