version: "3.7"
services:
  backend:
    build: ./backend
    restart: always
    container_name: backend
    hostname: backend
    env_file:
      - ./docker/.env
    ports:
      - "4000:4000"
    secrets:
      - backend_graphql_access_key
      - sentiment_access_key
      - elastic_password

  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    hostname: frontend
    env_file:
      - ./docker/.env
    environment:
      - BACKEND_ADDR=${BACKEND_ADDR}
    ports:
      - "80:80"


  sentiment:
    build: ./Sentiment
    restart: always
    container_name: sentiment
    hostname: sentiment
    env_file:
      - ./docker/.env
    ports:
      - "80:4001"
    secrets:
      - backend_access_key

<<<<<<< HEAD
  reddit_crawler:
    build: ./reddit-crawler
    restart: always
    container_name: reddit_crawler
    hostname: reddit_crawler
    secrets:
      - backend_access_key
      - reddit_login_password
      - reddit_client_secret
=======
#  reddit_crawler:
#    build: ./reddit-crawler
#    restart: always
#    container_name: reddit_crawler
#    hostname: reddit_crawler
#    secrets:
#      - backend_access_key
>>>>>>> 5e23193 (docker-compose update configuration environments)

#  shares_crawler:
#    build: ./shares_crawler
#    restart: always
#    container_name: shares_crawler
#    hostname: shares_crawler
#    secrets:
#      - backend_access_key

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    env_file:
      - ./docker/.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_SECURITY}
    secrets:
      - elastic_password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ports:
      - "${ELASTIC_PORT1}:$ELASTIC_PORT1}"
      - "${ELASTIC_PORT2}:$ELASTIC_PORT2}"
    healthcheck:
      test:
        [
        "CMD-SHELL",
        "curl --fail http://localhost:${ELASTIC_PORT1} || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


volumes:
  elastic-data:

secrets:
  backend_access_key:
    file: ./docker/secrets/backend_access_key.txt
  sentiment_access_key:
    file: ./docker/secrets/sentiment_access_key.txt
