version: "3.7"
services:
  backend:
    build: ./backend
    restart: always
    container_name: backend
    hostname: backend
    env_file:
      - ./docker/.env
    ports:
      - "4000:4000"
    secrets:
      - backend_access_key
      - sentiment_access_key

  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    hostname: frontend
    env_file:
      - ./docker/.env
    environment:
      - BACKEND_ADDR=${BACKEND_ADDR}
    ports:
      - "80:80"
    secrets:
      - backend_access_key


  sentiment:
    build: ./Sentiment
    restart: always
    container_name: sentiment
    hostname: sentiment
    env_file:
      - ./docker/.env
    ports:
      - "80:4001"
    secrets:
      - sentiment_access_key

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    env_file:
      - ./docker/.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_SECURITY}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
        "CMD-SHELL",
        "curl --fail http://localhost:9200 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


volumes:
  elastic-data:

secrets:
  backend_access_key:
    file: ./docker/secrets/backend_access_key.txt
  sentiment_access_key:
    file: ./docker/secrets/sentiment_access_key.txt
